spring.application.name=formapp

# 共通設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080

# Renderなどで環境変数が設定されている場合はPostgreSQLを使用
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/formapp}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console